

INDEXES = {'^GSPC': 'S&P 500',
           '^DJI': 'Dow Jones Industrial Average',
           '^IXIC': 'Nasdaq',
           '^NYA': "NYSE Composite",
           '^XAX': "NYSE Amex Composite",
           '^BUK100P': "CBOE UK 100",
           '^RUT': 'Russell 2000',
           '^VIX': "CBOE Volatility Index",
           '^FTSE': 'FTSE 100',
           '^GDAXI': "DAX Performance Index",
           '^FCHI': "CAC 40",
           '^IBEX': "IBEX 35",
           '^STOXX50E': "ESTX 50",
           '^N100': "Euronext 100",
           '^BFX': "BEL 20",
           'IMOEX.ME': "MOEX Russia Index",
           '^N225': 'Nikkei 225',
           '^HSI': "Hang Seng",
           '399001.SZ': "Shenzen Index",
           '^STI': "STI Index",
           '^JKSE': "IDX Composite",
           '^KS11': "KOSPI Composite Index",
           '^BVSP': "IBOVESPA",
           '^MXX': "IPC Mexico"}